name: 'tekartik_bootstrap'
version: 0.1.0
description: Boostrap wrappers
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  browser: any
  pub_semver: any
  tekartik_jquery:
    git:
      url: git://github.com/tekartik/jquery.dart
      ref: dart2
  tekartik_bootstrap_asset:
    git:
      url: git://github.com/tekartik/bootstrap_asset.dart
      ref: dart2
  dart_to_js_script_rewriter: any
dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
     git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
