name: 'tekartik_bootstrap'
version: 0.3.0
description: Boostrap wrappers
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  pub_semver: any
  tekartik_jquery:
    git:
      url: git://github.com/tekartik/jquery.dart
      ref: dart2
    version: '>=0.3.0'
  tekartik_bootstrap_asset:
    git:
      url: git://github.com/tekartik/bootstrap_asset.dart
      ref: dart2
dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
     git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
